# Generated by Django 4.1.7 on 2023-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_todomodel_key_alter_todomodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
